[package]
name = "pyi_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = {version = "1.0.85"}
quote = "1.0.36"
syn = {version="2.0.66", features=["full", "extra-traits"]}

[lib]
proc-macro = true


